# Generated by Django 3.2.1 on 2021-07-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_gam', models.CharField(max_length=30)),
                ('Desc_gam', models.CharField(max_length=300)),
                ('img_brand', models.ImageField(blank=True, null=True, upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_cat', models.CharField(max_length=30)),
                ('Desc_cat', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_prod', models.CharField(max_length=20)),
                ('Price', models.FloatField(blank=True)),
                ('Desc_prod', models.TextField(blank=True, max_length=1000)),
                ('Details', models.TextField(blank=True, max_length=1000)),
                ('img_prod', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nbr_stock', models.IntegerField()),
                ('Gender', models.CharField(blank=True, choices=[('W', 'Women'), ('M', 'Men'), ('M/W', 'Both')], max_length=100)),
                ('Rating', models.CharField(blank=True, choices=[('1', 'one star'), ('2', 'two stars'), ('3', 'three stars'), ('4', 'four stars'), ('5', 'five stars')], max_length=100)),
                ('is_sale', models.BooleanField(default=False)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesmerEyesApp.categories')),
                ('id_ga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesmerEyesApp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Album_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='Others/')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesmerEyesApp.product')),
            ],
        ),
    ]
