# Generated by Django 3.2.1 on 2021-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
