# Generated by Django 3.2.1 on 2021-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
